name: test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    container: osrf/ros:humble-desktop
    steps:
      - uses: actions/checkout@v3
      
      - name: Build and Test
        run: |
          mkdir -p ~/ros2_ws/src/mypkg
          cp -r . ~/ros2_ws/src/mypkg/
          cd ~/ros2_ws
        
          bash -xv src/mypkg/test/test.bash
